### ISSUE TITLE
Roadmap for v0.1

### ISSUE THREAD

**Issue by gorhom** [gorhom/react-native-base-ui#5]
With this release, I aim to release the very essential components and core setup for the library.

# Components
- [x] Button
- [x] Typography
- [x] Input
- [x] Icons

# Functionalities
- [x] Theming
- [x] Dark theme
- [x] Light theme
- [x] Add overriding functionality

# Documentation
- [x] Update readme file

# Development
- [x] Storybook
- [x] Setup component generator
